### ISSUE TITLE
Private repositories don't show

### ISSUE THREAD

**Issue by dburkes** [dennisreimann/ioctocat#11] opened 2009-04-30 04:04 UTC
iOctocat says I have no private repositories, when, in fact, I've got lots.

**Comment by dennisreimann** [comment] 2009-04-30 06:17
I don't have any private repositories myself, so I could check this, but it got reported to me by a friend too - I'll fix it :)

**Comment by intabulas** [comment] 2009-05-01 20:53
fixed in my fork, pull request sent

**Comment by intabulas** [comment] 2009-05-01 21:01
great.. all: dont forget to test viewing recent commits for private repo, both required changes

**Comment by dennisreimann** [comment] 2009-05-01 21:08
Thanks Mark, I applied your changes. Can someone verify that the problem is now solved? I don't have any private repos as I don't have a paid plan, yet.

**Comment by dennisreimann** [comment] 2009-05-02 18:09
This one got reported as fixed, but the recent commits for a private repository don't seem to show.

**Closed as completed** 2009-05-14 06:58 UTC
Labels: bug
