### ISSUE TITLE
Only a subset of starred Repositories are loaded into the Starred-List

### ISSUE THREAD

**Issue by senfomat** [dennisreimann/ioctocat#348] opened 2013-03-10 22:21 UTC
I've noticed, that in the list of my star-ed github-repos only 30 are loaded, without any possibility to load further. As I have 53 starred, I miss some of them.

**Comment by iosdeveloper** [comment] 2013-03-11 05:41
Duplicate of #177. Closing...

**Closed as completed by iosdeveloper** 2013-03-11 05:41 UTC

**Comment by dennisreimann** [comment] 2013-03-11 07:47
@senfomat we will address that soon, it will be done in v1.9 as other parts of the app also lack pagination.
