### ISSUE TITLE
"Open in"

### ISSUE THREAD

**Issue by AngryAnt** [dennisreimann/ioctocat#217] opened 2013-01-16 17:18 UTC
While I understand that you do not want to support a full git interface for editing, it would still be quite interesting if we were able to easily open files in other iOS apps.

I quite like using Textastic to scratch that late night "hey, what if I did...?" itch without booting a laptop. Being able to open files / importing from my github repositories would nicely reduce the time from thought to hack start. It would completely be a one way thing, but none the less quite useful.

Single file open would be great, but folder on top of that would be really awesome.

**Comment by dennisreimann** [comment] 2013-01-16 17:21
Duplicate of #205

**Closed as completed by dennisreimann** 2013-01-16 17:21 UTC
