### ISSUE TITLE
Jump to the right comment

### ISSUE THREAD

**Issue by semaperepelitsa** [dennisreimann/ioctocat#427] opened 2013-11-09 07:02 UTC
It is hard to read issue updates right now, because every time you tap a notification you start at the very top. The same applies to activity feed. GitHub website links to the right comments, that's what the app should do.

**Comment by dennisreimann** [comment] 2013-11-09 07:04
Yep, right now the API does not give me a way to know what kind of action triggered a notification (issue closed, reopened or new comment), but GitHub is informed. 

Once they add this I can implement it - thanks for this suggestion!

**Comment by lhunath** [comment] 2013-11-29 23:24
Would it be acceptable to just jump to the bottom of an issue rather than the top when we know the issue changed?  The top is usually the least interesting part.

**Comment by dennisreimann** [comment] 2013-11-29 23:28
The point is that the API does not tell you whether or not the issue is new or a comment was created. So there is no way to distinguish these events currently - you'd always go to the bottom, even for newly created issues. 

I'll try something like go downwards once the comments are loaded and there is at least one comment as I don't think GitHub will really act on this sometime soon.

**Comment by ruddfawcett** [comment] 2013-12-02 05:01
@dennisreimann do you think you could use the issue id to help with the scroll? Just a thought.  

Also, while typing this, it seems the textview inset is off on the right?  Forgive me if I'm wrong.

**Comment by dennisreimann** [comment] 2013-12-02 09:06
> do you think you could use the issue id to help with the scroll?

I think it is always set, I think the approach I described previously will work.

>  it seems the textview inset is off on the right?

What do you mean by that?

**Comment by dennisreimann** [comment] 2013-12-10 08:30
Done, will be part of the next release (v2.2.4) :)

**Closed as completed by dennisreimann** 2013-12-10 08:30 UTC
Labels: on hold, ui+ux
