### ISSUE TITLE
Load more commits

### ISSUE THREAD

**Issue by iosdeveloper** [dennisreimann/ioctocat#237] opened 2013-02-09 18:16 UTC
Currently only the first 30 (?) commits are displayed. I suggest loading the next bunch of commits when the user scrolls to the end of the list.

**Comment by iosdeveloper** [comment] 2013-02-09 21:45
Needed in other places where only a limited amount of items is loaded too.

**Comment by dennisreimann** [comment] 2013-02-09 22:10
Duplicate of #177

**Closed as completed by dennisreimann** 2013-02-09 22:10 UTC
